// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Leaflet = require("leaflet");

var CRS = /* module */[];

var Layer = /* module */[];

var Point = /* module */[];

var LatLngBounds = /* module */[];

var LatLng = /* module */[];

var $$Map = /* module */[];

var Control = /* module */[];

function create_lat_lng(latitude, longitude, altitude) {
  if (altitude) {
    return Leaflet.latLng(/* tuple */[
                latitude,
                longitude,
                altitude[0]
              ]);
  } else {
    return Leaflet.latLng(/* tuple */[
                latitude,
                longitude
              ]);
  }
}

exports.CRS = CRS;
exports.Layer = Layer;
exports.Point = Point;
exports.LatLngBounds = LatLngBounds;
exports.LatLng = LatLng;
exports.$$Map = $$Map;
exports.Control = Control;
exports.create_lat_lng = create_lat_lng;
/* leaflet Not a pure module */
